version: '3.8'

services:
  # Serviço do Laravel API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio_backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8081:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - portfolio_net
    depends_on:
      - db

  # Serviço do Angular Front
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      # Esta linha evita que a node_modules do container seja sobrescrita pela do Windows
      - /app/node_modules
    ports:
      - "4200:4200"
    networks:
      - portfolio_net
    command: sh -c "npm install && ng serve --host 0.0.0.0 --poll 2000"

  # Serviço de Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: ramon
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432" # Mapeia 5433 PC para 5432 Docker para evitar conflito
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - portfolio_net

  # Interface visual para o Banco
  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - portfolio_net
    depends_on:
      - db

networks:
  portfolio_net:
    driver: bridge

volumes:
  pgdata: